In [3]:
import numpy as np

In [5]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [8]:
matriz = np.array([[1,2,3], ["peixe", "a", "b"], [1,2,3]])

print(matriz)

[['1' '2' '3']
 ['peixe' 'a' 'b']
 ['1' '2' '3']]


In [18]:
arr = np.zeros([11,11])
print(arr)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [23]:
arr = np.ones([11,11], str)
print(arr)

[['1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1']]


In [26]:
for i in range(11):
    for j in range(11):
        if i == j:
            arr[i,j] = "X"
        elif 10-i == j:
            arr[i,j] = "X"
        else:
            arr[i,j] = "."

print(arr)

[['X' '.' '.' '.' '.' '.' '.' '.' '.' '.' 'X']
 ['.' 'X' '.' '.' '.' '.' '.' '.' '.' 'X' '.']
 ['.' '.' 'X' '.' '.' '.' '.' '.' 'X' '.' '.']
 ['.' '.' '.' 'X' '.' '.' '.' 'X' '.' '.' '.']
 ['.' '.' '.' '.' 'X' '.' 'X' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' 'X' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' 'X' '.' 'X' '.' '.' '.' '.']
 ['.' '.' '.' 'X' '.' '.' '.' 'X' '.' '.' '.']
 ['.' '.' 'X' '.' '.' '.' '.' '.' 'X' '.' '.']
 ['.' 'X' '.' '.' '.' '.' '.' '.' '.' 'X' '.']
 ['X' '.' '.' '.' '.' '.' '.' '.' '.' '.' 'X']]
