In [36]:
import numpy as np

arr1, arr2 = np.ones(8, dtype=int), np.random.randint(0,10,size=8)
print(arr1)
print(arr2)

arr3 = arr1 + arr2
print(arr3)
print(sum(arr3))

if sum(arr3) >= 40:
    print(arr3.reshape(4,2))
else:
    print(arr3.reshape(2,4))




[1 1 1 1 1 1 1 1]
[1 7 5 5 3 4 0 1]
[2 8 6 6 4 5 1 2]
34
[[2 8 6 6]
 [4 5 1 2]]


In [34]:
campo = np.zeros((2,2), dtype=int)

campo[np.random.randint(0, 2), np.random.randint(0, 2)] = 1
print(campo)

x,y = input("coordenada x [0,1]: "), input("coordenada y [0,1]: ")

jogadas_feitas = set()
perdeu = False

while len(jogadas_feitas) < 3:
    print(f"\n--- Jogada {len(jogadas_feitas) + 1} de 3 ---")
    linha = int(input("Informe a linha (0 ou 1): "))
    coluna = int(input("Informe a coluna (0 ou 1): "))

    if (linha, coluna) in jogadas_feitas:
        print("Você já escolheu essa posição. Tente outra!")
        continue

    jogadas_feitas.add((linha, coluna))

    if campo[linha, coluna] == 1:
        perdeu = True
        break
    else:
        print("Posição segura!")

# Resultado final
if perdeu:
    print("\nGame Over! :( Try Again!")
else:
    print("\nCongratulations! You beat the game! :)")

[[0 0]
 [0 1]]

--- Jogada 1 de 3 ---
Posição segura!

--- Jogada 2 de 3 ---
Posição segura!

--- Jogada 3 de 3 ---

Game Over! :( Try Again!


In [64]:
matriz = np.random.randint(1, 10, size=(3, 5))

linhas, colunas = matriz.shape

total_elementos = linhas * colunas

if total_elementos % 2 == 0:
    paridade = "par"
else:
    paridade = "ímpar"

print("Matriz gerada:")
print(matriz)
print(f"\nDimensões: {linhas} linhas e {colunas} colunas")
print(f"Total de elementos (linhas x colunas): {total_elementos}")
print(f"Esta matriz pode se tornar um vetor unidimensional com um número {paridade} de elementos.")


Matriz gerada:
[[7 5 4 1 5]
 [7 9 2 9 5]
 [2 4 7 6 4]]

Dimensões: 3 linhas e 5 colunas
Total de elementos (linhas x colunas): 15
Esta matriz pode se tornar um vetor unidimensional com um número ímpar de elementos.


In [62]:
np.random.seed(10)
matriz = np.random.randint(1, 51, size=(4,4))

print(f"media das linhas: {matriz.mean(axis=1)}")
print(f"media das colunas: {matriz.mean(axis=0)}\n")

print(f"media das linhas: {matriz.mean(axis=1).max()}")
print(f"media das colunas: {matriz.mean(axis=0).max()}\n")

valores, quant = np.unique(matriz, return_counts=True)
for val, count in zip(valores, quant):
    print(f"Número {val}: {count}x")

numeros_duas_vezes = valores[quant == 2]
print(f"\nNúmeros que aparecem exatamente 2 vezes: {numeros_duas_vezes}")

media das linhas: [16.   33.75 34.5  23.75]
media das colunas: [29.75 24.25 33.75 20.25]

media das linhas: 34.5
media das colunas: 33.75

Número 1: 2x
Número 9: 1x
Número 10: 2x
Número 16: 1x
Número 26: 1x
Número 29: 1x
Número 30: 2x
Número 37: 1x
Número 41: 1x
Número 43: 1x
Número 49: 1x
Número 50: 2x

Números que aparecem exatamente 2 vezes: [ 1 10 30 50]


In [67]:
mat1 = np.zeros((3,3), int)
mat2 = np.ones((3,3), int)
mat3 = np.empty((3,3), int)
for i in range(3):
    for j in range(3):
        mat3[i][j] = (mat1[i][j] + mat2[i][j])*5
print(mat3)

print(mat3.reshape(9))


[[5 5 5]
 [5 5 5]
 [5 5 5]]
[5 5 5 5 5 5 5 5 5]


In [70]:
import numpy as np

array = np.arange(10, 31, 2)

maior_valor = array.max()
indice_maior = array.argmax()

menor_valor = array.min()
indice_menor = array.argmin()

soma_elementos = array.sum()

print(f"Array gerado:\n{array}\n")
print(f"Maior valor: {maior_valor} | Índice: {indice_maior}")
print(f"Menor valor: {menor_valor} | Índice: {indice_menor}")
print(f"Soma de todos os elementos: {soma_elementos}")

Array gerado:
[10 12 14 16 18 20 22 24 26 28 30]

Maior valor: 30 | Índice: 10
Menor valor: 10 | Índice: 0
Soma de todos os elementos: 220


In [75]:
np.random.seed(7)
arr1, arr2 = np.random.randint(1, 11, size=5, dtype=int), np.random.randint(1, 11, size=5, dtype=int)

arr3 = np.concatenate((arr1, arr2))
print(arr3)

print(arr3.reshape(2,5))

[ 5 10  7  4  4  8  8 10  8  9]
[[ 5 10  7  4  4]
 [ 8  8 10  8  9]]
